name: Auto Label Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  call-labeler:
    uses: KathiraveluLab/.github/.github/workflows/labeler.yml@main
    with:
      issue_title: ${{ github.event.issue.title }}
      issue_body: ${{ github.event.issue.body }}
      issue_number: ${{ github.event.issue.number }}
      repo: ${{ github.repository }}
    secrets:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
